#  == File: prometheus-server.yml
#
# Install & Configure Prometheus Server
#
#  == Copyright
#     All Rights Reserved
#
# --------------------------------------------------------------------------
# WARNING: This file belongs to the Core framework. Avoid any local changes
# --------------------------------------------------------------------------
#
# This file is Managed by ANSIBLE
# --------------------------------------------------------------------------


    #- name: Create Prometheus User
    #  command: sudo useradd -m -s /bin/false prometheus

    - name: Create Prometheus Dir
      command: sudo mkdir -p /etc/prometheus; sudo mkdir -p /var/lib/prometheus; chown prometheus /var/lib/prometheus/

    - name: Download the Script
      command: wget https://github.com/prometheus/prometheus/releases/download/v2.14.0/prometheus-2.14.0.linux-amd64.tar.gz -P /tmp

    - name: Execute the Script
      command: cd /tmp

    - name: Execute the Script
      command: tar -zxpvf prometheus-2.14.0.linux-amd64.tar.gz;

    - name: Execute the Script
      command: cd prometheus-2.14.0.linux-amd64/

    - name: Execute the Script
      command: cd prometheus-2.14.0.linux-amd64/; cp prometheus  /usr/local/bin; cp promtool  /usr/local/bin

    - name: "Copy Prometheus Config .cfg File"
      copy:
        src:  "{{ansible_roles_path}}/files/prometheus/prometheus.yml"
        dest: /etc/prometheus/prometheus.yml
        owner: root
        group: root
        mode: '755'

    - name: "Copy Prometheus Systemd File"
      copy:
        src:  "{{ansible_roles_path}}/files/prometheus/prometheus.service"
        dest: /etc/systemd/system/prometheus.service
        owner: root
        group: root
        mode: '755'

    - name: Reload the systemd service
      command: systemctl daemon-reload; systemctl enable prometheus

          - name: Start and Enable Prometheus Service
      systemd:
        name: prometheus
        state: restarted
        enabled: yes

    - name: Execute the Script
      command: sudo rm -rf /tmp/*.gz

      
